export * from './display.resolver'
export * from './permisos/permisos.resolver'
export * from './rutap/entidades.resolver'
export * from './rutap/empresas.resolver'
export * from './permisos/logs.resolver'
